### ISSUE TITLE
Usability issue with respondWithFile

### ISSUE THREAD

**Issue by akc42** [nodejs/http2#183] opened 2017-07-16 10:27 UTC
I am trying to use respondWithFile to handle the static files in my application.  I am using the pattern that the "serve-static" module uses, namely that until I have managed the "stat" of a file as existing, any 'ENOENT' error should be just ignored and passed to the next middleware in my router stack.  If the reason I couldn't find the file was because it was a client side route, I can then respond with `index.html`

The code below is my function for serving the file.  As you can see, I have added an 'error' handler for the response stream, which would be the obvious thing to do since there is where the `respondWithFile` function is located.

```
    serveFile(url, req, res, next) {
      let forwardError = false;
      //helper for static files
      function statCheck(stat, headers) {
        headers['last-modified'] = stat.mtime.toUTCString();
        forwardError = true;
        return true; //tell it to continue
      }
      //we should have statically compiled client
      const clientPath = this.transformNeeded(req) ?
        process.env.PAS_CLIENT_ES5 :
        process.env.PAS_CLIENT_ES6;

      const filename = path.resolve(
        __dirname,
        clientPath,
        url.charAt(0) === '/' ? url.substring(1) : url
      );
      const ext = path.extname(filename);

      requestLog(`send static file ${filename}`);
      res.stream.on('error', err => {
        if (forwardError || !(err.code === 'ENOENT') {
          next(err);
        } else {
          //this was probably file not found, in which case we just go to next middleware function.
          next();
        }
      });
      res.stream.respondWithFile(
        filename,
        { 'content-type': map[ext] || 'text/plain' },
        { statCheck });
    }
```
**However** there are actually two error events fired for non-existing files, and neither of them are on the response.stream. One is on the request, and one is on the response.  The documents don't really give any clue to this, and it means a rather cludgy solution

```
      res.on('error', err => {
        if (forwardError || !(err.code === 'ENOENT')) {
          next(err);
        } else {
          //this was file not found, in which case we just go to next middleware function.
          next();
        }
      });
      req.on('error', err => {
        if(err.code !== 'ENOENT') {
          next(err);
        }
      });
```
And I am still not sure that I am not going to end up doing something strange with errors that are not 'ENOENT'

**Comment by akc42** [comment] 2017-07-16 10:30
I just realised this is 
https://github.com/nodejs/http2/issues/168
expressed a different way

**Comment by jasnell** [comment] 2017-07-19 14:52
Going to close this as a duplicate of #168 :-)

**Closed as completed by jasnell** 2017-07-19 14:52 UTC
